application: calendrier-de
version: 1
runtime: go
api_version: go1

handlers:
- url: /.well-known/acme-challenge/(.*)
  mime_type: text/plain
  static_files: well-known/acme-challenge/\1
  upload: well-known/acme-challenge/.*

- url: /static
  static_dir: static

- url: /.*
  script: _go_app